version: '3.7'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

  elasctic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    labels:
      co.elastic.logs/module: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - node.name=elasctic
      - cluster.name=test
      - discovery.type=single-node
      - ELASTIC_PASSWORD=toor
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
