version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pets
      MONGODB_USER: user
      MONGODB_PASS: password
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

  elasctic:
    version: '3'
    services:
      elasticsearch:
        image: elasticsearch:8.8.0
        ports:
          - 9200:9200
          - 9300:9300
        environment:
          - discovery.type=single-node
          - xpack.security.enabled=false
